=== KariimAlii/ITI/XML/Lab2/Task2/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Contacts">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded" >
				<xs:element name="employee">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name"></xs:element>
							<xs:element name="phones">
								<xs:complexType>
									<xs:sequence minOccurs="0" maxOccurs="unbounded" >
										<xs:element name="phone">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string" >
														<xs:attribute name="type" type="phoneType"></xs:attribute>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
										
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="adresses">
								<xs:complexType>
									<xs:sequence minOccurs="0" maxOccurs="unbounded" >
										<xs:element name="address">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="street" type="xs:string"></xs:element>
													<xs:element name="building" type="xs:string"></xs:element>
													<xs:element name="number" type="xs:int"></xs:element>
													<xs:element name="region" type="xs:string"></xs:element>
													<xs:element name="city" type="xs:string"></xs:element>
													<xs:element name="country" type="xs:string"></xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="email" type="emailAddress"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>			
		</xs:complexType>
	</xs:element>
	
	
	<xs:simpleType name="phoneType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="home"/>
			<xs:enumeration value="work"/>
			<xs:enumeration value="mobile"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="emailAddress">
		<xs:restriction base="xs:string">
			<xs:pattern value="[^@]+@[^\.]+\..+"></xs:pattern>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== KariimAlii/ITI/XML/Lab2/Task2/Task2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="style.css" type="text/css"?>
<Contacts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/Web/My%20Github/ITI/XML/Lab2/Task2/schema.xsd">
	<employee>
		<name>Karim Ali</name>
		<phones>
			<phone type="home">+201222768979</phone>
			<phone type="work">+203534567</phone>
			<phone type="mobile">+201045667789</phone>
		</phones>
		<adresses>
			<address>
				<street>Cairo</street>
				<building>Jebril</building>
				<number>10</number>
				<region>Sidi Beshr</region>
				<city>Alexandria</city>
				<country>Egypt</country>
			</address>
			<address>
				<street>Cairo</street>
				<building>Jebril</building>
				<number>10</number>
				<region>Sidi Beshr</region>
				<city>Alexandria</city>
				<country>Egypt</country>
			</address>
			<address>
				<street>Cairo</street>
				<building>Jebril</building>
				<number>10</number>
				<region>Sidi Beshr</region>
				<city>Alexandria</city>
				<country>Egypt</country>
			</address>
		</adresses>
		<email>kariimalii96@gmail.com</email>
	</employee>
	<employee>
		<name>Karim Ali</name>
		<phones>
			<phone type="home">+201222768979</phone>
			<phone type="work">+203534567</phone>
			<phone type="mobile">+201045667789</phone>
		</phones>
		<adresses>
			<address>
				<street>Cairo</street>
				<building>Jebril</building>
				<number>10</number>
				<region>Sidi Beshr</region>
				<city>Alexandria</city>
				<country>Egypt</country>
			</address>
			<address>
				<street>Cairo</street>
				<building>Jebril</building>
				<number>10</number>
				<region>Sidi Beshr</region>
				<city>Alexandria</city>
				<country>Egypt</country>
			</address>
			<address>
				<street>Cairo</street>
				<building>Jebril</building>
				<number>10</number>
				<region>Sidi Beshr</region>
				<city>Alexandria</city>
				<country>Egypt</country>
			</address>
		</adresses>
		<email>kariimalii96@gmail.com</email>
	</employee>
</Contacts>
